### ISSUE TITLE
ERROR lors du lancement du playbook

### ISSUE THREAD

**Issue by MaximeALLAN** [MaximeALLAN/Seedbox-Infra#1]
Erreur lors de l'execution de la commande `ansible-playbook -i provisioning/seedbox.yml provisioning/hosts` --> ERROR: provisioning/seedbox.yml:2: Invalid ini entry: name: - need more than 1 value to unpack

**Comment by JEDIBC** [comment]
avec `-i` tu précises ton fichier host, pas ton playbook

**Comment by MaximeALLAN** [comment]
la bonne commande est `ansible-playbook -i provisioning/hosts provisioning/seedbox.yml`
